[package]
name = "libxcrypt"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/besser82/libxcrypt/archive/v4.4.22/libxcrypt-4.4.22.tar.gz"
sha512 = "360c5df9a8a239c8e63b5edeea4c99f451fe67c0ef3084f7659c9ad4c976486bb09328fa1e731238538d7ea05133078d4f890d11c030aaee7734ea6f4ae28b1c"

[build-dependencies]
glibc = { path = "../glibc" }
