[package]
name = "systemd"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/systemd/systemd-stable/archive/v248.3/systemd-stable-248.3.tar.gz"
sha512 = "8e7ff0d5e63cc933e4dc23f7e0bef9707fde90396605eb8822d34de90d7abe8fd37e5739e33b657868218aa7281147cc944c096c007324c3e6fb54d833a83485"

[build-dependencies]
glibc = { path = "../glibc" }
kmod = { path = "../kmod" }
libacl = { path = "../libacl" }
libattr = { path = "../libattr" }
libcap = { path = "../libcap" }
libseccomp = { path = "../libseccomp" }
libselinux = { path = "../libselinux" }
libxcrypt = { path = "../libxcrypt" }
util-linux = { path = "../util-linux" }
