[package]
name = "kernel-5_4"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
package-name = "kernel-5.4"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/3166b2c4af7dbb50ef04eedc98aff0020ea1570892d7e01a9dab885e04168afc/kernel-5.4.117-58.216.amzn2.src.rpm"
sha512 = "0d86948018725b4590622a49f27fa7dae03ce06fcef11d39883f7fc421087442fea54c30603c997bd6f519606be596f1e46f33727213c34bd78a85076a47eeef"

# RPM BuildRequires
[build-dependencies]
# Provided by Bottlerocket SDK
